# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mackerz/Projects/hair-pathtracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mackerz/Projects/hair-pathtracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mackerz/Projects/hair-pathtracer/CMakeFiles /home/mackerz/Projects/hair-pathtracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mackerz/Projects/hair-pathtracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/mackerz/Projects/hair-pathtracer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dependencies

# Build rule for target.
Dependencies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dependencies
.PHONY : Dependencies

# fast build rule for target.
Dependencies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dependencies.dir/build.make CMakeFiles/Dependencies.dir/build
.PHONY : Dependencies/fast

#=============================================================================
# Target rules for targets named Framework

# Build rule for target.
Framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Framework
.PHONY : Framework

# fast build rule for target.
Framework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/build
.PHONY : Framework/fast

#=============================================================================
# Target rules for targets named Pathtracer

# Build rule for target.
Pathtracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pathtracer
.PHONY : Pathtracer

# fast build rule for target.
Pathtracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathtracer.dir/build.make CMakeFiles/Pathtracer.dir/build
.PHONY : Pathtracer/fast

acceleration/sah_bvh.o: acceleration/sah_bvh.cpp.o
.PHONY : acceleration/sah_bvh.o

# target to build an object file
acceleration/sah_bvh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/acceleration/sah_bvh.cpp.o
.PHONY : acceleration/sah_bvh.cpp.o

acceleration/sah_bvh.i: acceleration/sah_bvh.cpp.i
.PHONY : acceleration/sah_bvh.i

# target to preprocess a source file
acceleration/sah_bvh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/acceleration/sah_bvh.cpp.i
.PHONY : acceleration/sah_bvh.cpp.i

acceleration/sah_bvh.s: acceleration/sah_bvh.cpp.s
.PHONY : acceleration/sah_bvh.s

# target to generate assembly for a file
acceleration/sah_bvh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/acceleration/sah_bvh.cpp.s
.PHONY : acceleration/sah_bvh.cpp.s

bxdf/marschner_hair.o: bxdf/marschner_hair.cpp.o
.PHONY : bxdf/marschner_hair.o

# target to build an object file
bxdf/marschner_hair.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/bxdf/marschner_hair.cpp.o
.PHONY : bxdf/marschner_hair.cpp.o

bxdf/marschner_hair.i: bxdf/marschner_hair.cpp.i
.PHONY : bxdf/marschner_hair.i

# target to preprocess a source file
bxdf/marschner_hair.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/bxdf/marschner_hair.cpp.i
.PHONY : bxdf/marschner_hair.cpp.i

bxdf/marschner_hair.s: bxdf/marschner_hair.cpp.s
.PHONY : bxdf/marschner_hair.s

# target to generate assembly for a file
bxdf/marschner_hair.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/bxdf/marschner_hair.cpp.s
.PHONY : bxdf/marschner_hair.cpp.s

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/camera.cpp.s
.PHONY : camera.cpp.s

dep/glm/detail/glm.o: dep/glm/detail/glm.cpp.o
.PHONY : dep/glm/detail/glm.o

# target to build an object file
dep/glm/detail/glm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dependencies.dir/build.make CMakeFiles/Dependencies.dir/dep/glm/detail/glm.cpp.o
.PHONY : dep/glm/detail/glm.cpp.o

dep/glm/detail/glm.i: dep/glm/detail/glm.cpp.i
.PHONY : dep/glm/detail/glm.i

# target to preprocess a source file
dep/glm/detail/glm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dependencies.dir/build.make CMakeFiles/Dependencies.dir/dep/glm/detail/glm.cpp.i
.PHONY : dep/glm/detail/glm.cpp.i

dep/glm/detail/glm.s: dep/glm/detail/glm.cpp.s
.PHONY : dep/glm/detail/glm.s

# target to generate assembly for a file
dep/glm/detail/glm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dependencies.dir/build.make CMakeFiles/Dependencies.dir/dep/glm/detail/glm.cpp.s
.PHONY : dep/glm/detail/glm.cpp.s

geometry/curve.o: geometry/curve.cpp.o
.PHONY : geometry/curve.o

# target to build an object file
geometry/curve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/curve.cpp.o
.PHONY : geometry/curve.cpp.o

geometry/curve.i: geometry/curve.cpp.i
.PHONY : geometry/curve.i

# target to preprocess a source file
geometry/curve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/curve.cpp.i
.PHONY : geometry/curve.cpp.i

geometry/curve.s: geometry/curve.cpp.s
.PHONY : geometry/curve.s

# target to generate assembly for a file
geometry/curve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/curve.cpp.s
.PHONY : geometry/curve.cpp.s

geometry/sphere.o: geometry/sphere.cpp.o
.PHONY : geometry/sphere.o

# target to build an object file
geometry/sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/sphere.cpp.o
.PHONY : geometry/sphere.cpp.o

geometry/sphere.i: geometry/sphere.cpp.i
.PHONY : geometry/sphere.i

# target to preprocess a source file
geometry/sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/sphere.cpp.i
.PHONY : geometry/sphere.cpp.i

geometry/sphere.s: geometry/sphere.cpp.s
.PHONY : geometry/sphere.s

# target to generate assembly for a file
geometry/sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/geometry/sphere.cpp.s
.PHONY : geometry/sphere.cpp.s

image.o: image.cpp.o
.PHONY : image.o

# target to build an object file
image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/image.cpp.o
.PHONY : image.cpp.o

image.i: image.cpp.i
.PHONY : image.i

# target to preprocess a source file
image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/image.cpp.i
.PHONY : image.cpp.i

image.s: image.cpp.s
.PHONY : image.s

# target to generate assembly for a file
image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/image.cpp.s
.PHONY : image.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/parser.cpp.s
.PHONY : parser.cpp.s

pathtracer.o: pathtracer.cpp.o
.PHONY : pathtracer.o

# target to build an object file
pathtracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/pathtracer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathtracer.dir/build.make CMakeFiles/Pathtracer.dir/pathtracer.cpp.o
.PHONY : pathtracer.cpp.o

pathtracer.i: pathtracer.cpp.i
.PHONY : pathtracer.i

# target to preprocess a source file
pathtracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/pathtracer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathtracer.dir/build.make CMakeFiles/Pathtracer.dir/pathtracer.cpp.i
.PHONY : pathtracer.cpp.i

pathtracer.s: pathtracer.cpp.s
.PHONY : pathtracer.s

# target to generate assembly for a file
pathtracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/pathtracer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pathtracer.dir/build.make CMakeFiles/Pathtracer.dir/pathtracer.cpp.s
.PHONY : pathtracer.cpp.s

scene.o: scene.cpp.o
.PHONY : scene.o

# target to build an object file
scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/scene.cpp.o
.PHONY : scene.cpp.o

scene.i: scene.cpp.i
.PHONY : scene.i

# target to preprocess a source file
scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/scene.cpp.i
.PHONY : scene.cpp.i

scene.s: scene.cpp.s
.PHONY : scene.s

# target to generate assembly for a file
scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/scene.cpp.s
.PHONY : scene.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Framework.dir/build.make CMakeFiles/Framework.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Dependencies"
	@echo "... Framework"
	@echo "... Pathtracer"
	@echo "... acceleration/sah_bvh.o"
	@echo "... acceleration/sah_bvh.i"
	@echo "... acceleration/sah_bvh.s"
	@echo "... bxdf/marschner_hair.o"
	@echo "... bxdf/marschner_hair.i"
	@echo "... bxdf/marschner_hair.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... dep/glm/detail/glm.o"
	@echo "... dep/glm/detail/glm.i"
	@echo "... dep/glm/detail/glm.s"
	@echo "... geometry/curve.o"
	@echo "... geometry/curve.i"
	@echo "... geometry/curve.s"
	@echo "... geometry/sphere.o"
	@echo "... geometry/sphere.i"
	@echo "... geometry/sphere.s"
	@echo "... image.o"
	@echo "... image.i"
	@echo "... image.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... pathtracer.o"
	@echo "... pathtracer.i"
	@echo "... pathtracer.s"
	@echo "... scene.o"
	@echo "... scene.i"
	@echo "... scene.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/mackerz/Projects/hair-pathtracer/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

